services:
  backend-dev:
    container_name: rbx-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    ports:
      - '8000:8000'
    # environment:
    #   - APPLICATION_PORT=8000
    #   - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - db
    profiles:
      - dev

  # production backend service
  backend-prod:
    container_name: rbx-backend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    ports:
      - '8080:8080'
    # environment:
    #   - APPLICATION_PORT=8000
    #   - NODE_ENV=production
    depends_on:
      - db
    profiles:
      - prod

  # database service for postgres
  db:
    image: postgres:14
    container_name: rbx-db
    env_file:
      - .env.dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgadmin service for postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: rbx-pgadmin
    restart: always
    env_file:
      - .env.dev
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:
