# Step 1: Use an official Node.js runtime as a parent image
FROM node:18 as development

# Step 2: Set the working directory inside the container
WORKDIR /usr/src/app

# Step 3: Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Step 4: Install the application dependencies
RUN npm install

# Step 3: Copy everything from the current directory to the working directory
COPY . .

# Step 7: Expose the application port (default is 8000)
EXPOSE 8000

# Step 8: Define the command to start the application
CMD ["npm", "run", "start:dev"]
